name: Build Kate Plugin (Windows x64)

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-2022

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Installa Qt6 Ufficiale
      uses: jurplel/install-qt-action@v3
      with:
        version: '6.10.1'
        arch: 'win64_msvc2022_64'
        modules: 'qtbase'

    - name: Configura MSVC Compiler
      uses: ilammy/msvc-dev-cmd@v1

    - name: Configura CMake
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_BUILD_TYPE=Release ..

    - name: Compila Plugin C++
      run: |
        cd build
        cmake --build . --config Release

    - name: Rilascia file DLL pronto
      uses: actions/upload-artifact@v4
      with:
        name: customfoldingplugin-windows-x64
        path: build/Release/customfoldingplugin.dll
